var currenciesJSON = 
{	
	USD: { name: 'US Dollar' },
	EUR: { name: 'Euro' },
	JPY: { name: 'Japanese Yen' },
	BGN: { name: 'Bulgarian Lev' },
	CZK: { name: 'Czech Koruna' },
	DKK: { name: 'Danish Krone' },
	GBP: { name: 'Pound Sterling' },
	HUF: { name: 'Hungarian Forint' },
	PLN: { name: 'Polish Zloty' },
	RON: { name: 'Romanian Leu' },
	SEK: { name: 'Swedish Krona' },
	CHF: { name: 'Swiss Franc' },
	ISK: { name: 'Icelandic Krona' },
	NOK: { name: 'Norwegian Krone' },
	HRK: { name: 'Croatian Kuna' },
	RUB: { name: 'Russian Rouble' },
	TRY: { name: 'Turkish Lira' },
	AUD: { name: 'Australian Dollar' },
	BRL: { name: 'Brazilian Real' },
	CAD: { name: 'Canadian Dollar' },
	CNY: { name: 'Chinese Yuan' },
	HKD: { name: 'Hong Kong Dollar' },
	IDR: { name: 'Indonesian Rupiah' },
	ILS: { name: 'Israeli Shekel' },
	INR: { name: 'Indian Rupee' },
	KRW: { name: 'South Korean Won' },
	MXN: { name: 'Mexican Peso' },
	MYR: { name: 'Malaysian Ringgit' },
	NZD: { name: 'New Zealand Dollar' },
	PHP: { name: 'Philippine Peso' },
	SGD: { name: 'Singapore Dollar' },
	THB: { name: 'Thai Baht' },
	ZAR: { name: 'South African Rand' },	
	BTC: { name: 'Bitcoin' },	
}